version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
  reports:
    build:
      context: ./reports
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      KEYCLOAK_CLIENT_ID: reports-frontend
      KEYCLOAK_URL: http://keycloak:8080/realms/reports-realm
      ISSUER_URL: http://localhost:8080/realms/reports-realm
      ORIGINS: http://localhost:3000
      DATABASE_URL: postgresql://reports_user:reports_password@localhost:5434/reports_db
    depends_on:
      - keycloak
  reports_db:
    image: postgres:14
    environment:
      POSTGRES_DB: reports_db
      POSTGRES_USER: reports_user
      POSTGRES_PASSWORD: reports_password
    volumes:
      - ./postgres-reports-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
